#45 y #70 terminadas, pendientes de revision
Marthox1999/Nova pull request #102
Opened 2019-07-31 14:44 UTC by Marthox1999

2019-08-07 17:40 UTC, emyesme reviewed
hola, el #45 para mi esta bien :D el #70 no me deja crear descuento de producto

2019-08-08 02:35 UTC, emyesme submitted a review, later dismissed

2019-08-13 18:25 UTC, Shinku24 requested changes
Hay problemas con la validación de los datos, no se realiza FullClean por lo que acepta datos inválidos

Las interfaces están malas, debe quitarse el fondo blanco del fondo y ademas el titulo va en un cuadro blanco, mirar crearReferencias u otra interfaz que ya tenga el modelo

En la página de categorias elimiinar es el último boton no el segundo.

2019-08-14 20:35 UTC, emyesme submitted a review, later dismissed

2019-08-14 21:55 UTC, Shinku24 requested changes
Creo que es mejor para el usuario poner Onchange en vez de onClick para los combobox

Como Minimo que se coloquen valores por defecto en los combobox para que no parezca que ya se ha seleccionado algo

2019-08-16 00:10 UTC, emyesme approved these changes

2019-08-16 22:05 UTC, Shinku24 approved these changes

2019-08-16 22:25 UTC, merged