#20 y #22 Terminadas y listas para probar (SIGUIENTE SPRINT)
Marthox1999/Nova pull request #112
Opened 2019-08-15 21:52 UTC by Shinku24

2019-08-15 23:29 UTC, emyesme reviewed
-_- primero termina esta felipito, en todo caso pon sprint 3, sin mayusculas

2019-08-16 22:03 UTC, Shinku24 commented
Listo (por eso puse siguiente sprint :smiley: )

2019-08-19 20:23 UTC, emyesme requested changes
verificar precio, salta error con caracteres, el menu de hacer crud a referencia y producto no deberia ser un grid? botones cuadrados como los demas?

2019-08-23 02:54 UTC, emyesme approved these changes
En eliminar categoria no borra imagen de la carpeta, pero no me parece relevante.

2019-08-23 02:57 UTC, emyesme requested changes
en referencia modificar no carga iva, y eliminar categoria no borra imagen de carpeta (pero esta no es necesaria)

2019-08-23 20:28 UTC, Valeriarm approved these changes
Todo esta funcional y lindo <3

2019-08-23 20:49 UTC, emyesme approved these changes

2019-08-23 20:50 UTC, merged