modifica subcategoria, detalles de producto y agrega a carrito
Marthox1999/Nova pull request #115
Opened 2019-08-19 06:05 UTC by emyesme

#55, #11 y #12 pendientes de revision

ingresa como administrador, categorias, modificar categoria, modificar subcategoria existente

ingresa o no como cliente, selecciona producto y se muestran los detalles dando opcion de diferentes tallas y colores, que representan el detalle de producto

en la pantalla anteriormente explicada si esta ingresado esta el boton de agregar a carrito con una cantidad de productos dado.

Nota: en esta rama esta configurado un entrypoint por lo que solo es necesario hacer docker-compose up para migrar y crear el superusuario, (mas detalles en el readme)..
No es el definitivo porque se corre siempre al hacer up, asi que si hacen cambios no se nota, diria que sirve por ahora para pruebas cargar tanta informacion es tedioso.

Con los datos de mateo seria muy comodo para reportes

2019-08-20 16:35 UTC, Shinku24 requested changes
-Zapatosmujer1 es dificil de seleccionar
-Zapatosmujer4,3,2 da error de "list index out of range" (Pasa lo mismo con los de hombre)
-Al poner el cursor en zapatosmujer2 se corre zapatosmujer1
-Al bajar el cursor al Haber min 4 productos vuelve la pantalla arriba

-Cuando se ve los detalle de producto se debe cambiar el valor del precio que muestra o poner un precio bruto que multiplique el valor por la cantidad

2019-08-23 14:48 UTC, Shinku24 submitted a review, later dismissed
:+1:

2019-08-23 23:36 UTC, marthox submitted a review, later dismissed
Muy buen trabajo Emily :3 te quiero <3

2019-08-23 23:38 UTC, marthox approved these changes
Muy buen trabajo Mily, te quiero :3 <3

2019-08-24 00:12 UTC, JaimeCuartas approved these changes

2019-08-24 00:12 UTC, merged