HU D-9 #33 y D-5 #5
Marthox1999/Nova pull request #121
Opened 2019-08-24 13:51 UTC by Marthox1999

Para acceder a reportes debe usar el path: /reportes/inicioReportes o puedes entrar desde los menus de admin y duenio

Para acceder a eliminar admin debes ir al path: /usuarios/duenioAdminEliminar o puedes entrar desde el menu de duenio

2019-08-24 17:21 UTC, emyesme reviewed
si selecciono una fecha en desorden no genera reporte pero si la genero en orden si, sugiero se muestre un aviso de intervalo de fecha invalido.
Si selecciono solo una de las fecha ya sea inicio o fin doy click en generar reporte genera error

Exception Type:  ValueError
time data '' does not match format '%Y-%m-%d'

2019-08-25 19:42 UTC, emyesme submitted a review, later dismissed
bien

2019-08-30 13:23 UTC, Shinku24 requested changes
- No es "eliminar empleado" si no "Despedir empleado".
- En static/images/menu-CRUD hay una imagen para despedir.
- Al despedir un empleado no dice un mensaje de "El empleado fue despedido exitosamente" o algo así.
- Para el reporte, que la fecha no desaparezca o que tenga un titulo como reporte de >fecha1> a >fecha2>
- La interfaz esta mala, únicamente el reporte y el titulo "Reporte de ventas" deben estar en el cuadro blanco

2019-08-30 22:15 UTC, emyesme submitted a review, later dismissed

2019-08-31 15:50 UTC, Shinku24 approved these changes

2019-08-31 17:10 UTC, JaimeCuartas approved these changes

2019-08-31 19:33 UTC, merged