Terminada #32, #25, #23,  #125, #69, #65, #15
Marthox1999/Nova pull request #126
Opened 2019-09-04 00:37 UTC by Shinku24

#32 -> Desde dueño -> reportes-> Top Clientes
#25 -> Desde administrador -> reportes -> Top Clientes
#23 -> Desde administrador -> reportes -> Reporte de ventas por categoria
#125 -> Desde dueño -> reportes -> Reporte de ventas por categoria
#69 -> Desde dueño -> Bodegas -> Eliminar
#65 -> Desde administrador -> Bodegas -> Eliminar
#15 -> Cliente -> perfil -> mis compras

2019-09-05 23:12 UTC, Valeriarm approved these changes
#65 y #69 Funcionan bien, no se si se debería Mostar un mensaje de confirmación para eliminar.
Algunos links de las imágenes de los productos y las categorías me salen rotos, pero puede ser mi pc. 
Lo demás todo funciona bien :)

2019-09-05 23:36 UTC, Valeriarm requested changes
Cuando vas a ver un reporte del top de clientes y no le pasas nada se genera un error

2019-09-06 20:37 UTC, Valeriarm submitted a review, later dismissed

2019-09-06 21:00 UTC, Valeriarm submitted a review, later dismissed

2019-09-06 21:47 UTC, emyesme approved these changes

2019-09-06 21:50 UTC, Valeriarm approved these changes

2019-09-06 21:50 UTC, merged