Jaime 1632664
Marthox1999/Nova pull request #128
Opened 2019-09-04 22:18 UTC by Jaime1998

-http://localhost:8000/usuarios/clienteEliminar/<NombreDelCliente> , para la eliminación de un cliente

-http://localhost:8000/reportes/masVendidos/, para  la tabla que muestra los primeros 20 articulos más vendidos ordenados

-http://localhost:8000/reportes/menosVendidos/, para la tabla que muestra los primeros 20 articulos menos vendidos ordenados

-http://localhost:8000/ventas/descuentoCrud, cree esta ventana y no le puse /ventas/descuento porque ya existe pero no recuerdo en donde se usaba

-http://localhost:8000/ventas/descuentoConsultar, para consultar los descuentos, se genera una tabla y se debe seleccionar a traves de un radio button el tipo de consulta que se desea

2019-09-05 14:26 UTC, Shinku24 reviewed
* Cuando uno juega con la url y escribe un nombre de usuario (cliente) no registrado igual entra al sistema (no tiene que ver con las func implementadas solo lo descubrí)

* He estado mirando para ver si las tablas quedan mejor en fondo blanco o no

2019-09-05 14:27 UTC, Shinku24 requested changes
* En consultar descuentos que se quede seleccionado el radioButton o que exista un titulo que indique sobre cual de las tres opciones estoy consultando

2019-09-06 19:53 UTC, Shinku24 submitted a review, later dismissed

2019-09-06 20:59 UTC, Shinku24 submitted a review, later dismissed

2019-09-07 01:35 UTC, emyesme approved these changes
hay que estar pendientes de conectar estas ventanas

2019-09-07 02:51 UTC, Shinku24 approved these changes

2019-09-07 15:32 UTC, merged